./raw_amplitudes_only.bash ../../evolution_of_modularity/raw_data/027_Combinatoric_Echo_Backbone/ ../../evolution_of_modularity/analysis/027/
./raw_amplitudes_only.bash ../../evolution_of_modularity/raw_data/028_Combinatoric_Not_Backbone/ ../../evolution_of_modularity/analysis/028/
./raw_amplitudes_only.bash ../../evolution_of_modularity/raw_data/029_Combinatoric_Nand_Backbone/ ../../evolution_of_modularity/analysis/029/
./raw_amplitudes_only.bash ../../evolution_of_modularity/raw_data/030_Combinatoric_And_Backbone/ ../../evolution_of_modularity/analysis/030/
./raw_amplitudes_only.bash ../../evolution_of_modularity/raw_data/031_Combinatoric_Orn_Backbone/ ../../evolution_of_modularity/analysis/031/
./raw_amplitudes_only.bash ../../evolution_of_modularity/raw_data/032_Combinatoric_Or_Backbone/ ../../evolution_of_modularity/analysis/032/
./raw_amplitudes_only.bash ../../evolution_of_modularity/raw_data/033_Combinatoric_Andn_Backbone/ ../../evolution_of_modularity/analysis/033/
./raw_amplitudes_only.bash ../../evolution_of_modularity/raw_data/034_Combinatoric_Nor_Backbone/ ../../evolution_of_modularity/analysis/034/
./raw_amplitudes_only.bash ../../evolution_of_modularity/raw_data/035_Combinatoric_Xor_Backbone/ ../../evolution_of_modularity/analysis/035/
./raw_amplitudes_only.bash ../../evolution_of_modularity/raw_data/036_Combinatoric_Equ_Backbone/ ../../evolution_of_modularity/analysis/036/
./raw_amplitudes_only.bash ../../evolution_of_modularity/raw_data/037_Andn_Orn_Or__Opinion_Backbone/ ../../evolution_of_modularity/analysis/037/
./raw_amplitudes_only.bash ../../evolution_of_modularity/raw_data/038_Opinion__Andn_Orn_Or_Backbones/ ../../evolution_of_modularity/analysis/038/
